name: flutter_login_simple
description: Simple Flutter Firebase Authentication widget for email. Create, delete and reset password of account.
repository: https://github.com/xErik/flutter_login_simple
issue_tracker: https://github.com/xErik/flutter_login_simple/issues
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.5
  # get: ^4.6.5
  # firebase_auth: ^3.11.2
  # firebase_auth_web: ^4.6.1
  # flutter_widget_from_html_core: ^0.10.0
  # # firebase_core: ^1.24.0
  # firebase_core: ^2.9.0
  # firebase_core_web: ^1.7.3
  # firebase_auth_desktop: ^1.0.2
  # firebase_core_desktop: ^1.0.2

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  firebase_auth: ^4.4.0
  firebase_auth_web: ^5.3.0
  flutter_widget_from_html_core: ^0.10.0
  firebase_core: ^2.9.0
  firebase_core_web: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^2.0.1
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
